-- SEC-147 CANDIDATE MIGRATION
-- STATUS: CANDIDATE ONLY / NOT EXECUTED
-- Production deployment is NOT authorized by this file.
-- This migration must be executed only in a controlled environment whose 90-table
-- CargoDesk baseline has first been reconstructed and verified.
--
-- Purpose:
--   Add the four frozen readiness tables without altering existing operational tables.
--   Reuse logistics.audit_log for audit events.
--   Use explicit evidence-source foreign keys; no polymorphic source references.
--
-- IMPORTANT:
--   Permission rows, final audit action vocabulary, and exact cross-shipment validator
--   signature remain subject to controlled-environment verification and owner approval.
--
-- Expected post-migration table count in a verified baseline: 94.

begin;

-- Fail fast if the required existing foundation is not present.
do $$
declare
  v_tables integer;
begin
  select count(*) into v_tables
  from information_schema.tables
  where table_schema = 'logistics' and table_type = 'BASE TABLE';

  if v_tables <> 90 then
    raise exception 'SEC-147 preflight failed: expected 90 logistics base tables, found %', v_tables;
  end if;

  if to_regclass('logistics.shipments') is null
     or to_regclass('logistics.users') is null
     or to_regclass('logistics.audit_log') is null
     or to_regclass('logistics.shipment_documents') is null
     or to_regclass('logistics.proof_of_delivery') is null
     or to_regclass('logistics.delivery') is null then
    raise exception 'SEC-147 preflight failed: required existing CargoDesk tables are missing';
  end if;
end $$;

create table logistics.readiness_evaluation (
  readiness_evaluation_id bigint generated by default as identity primary key,
  shipment_id bigint not null references logistics.shipments(shipment_id),
  evaluation_version integer not null,
  lifecycle_status text not null,
  system_result text not null,
  rule_set_version text not null,
  evaluated_by bigint references logistics.users(user_id),
  evaluated_at timestamptz,
  summary text,
  rationale text,
  evidence_snapshot_reference text,
  supersedes_evaluation_id bigint references logistics.readiness_evaluation(readiness_evaluation_id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint readiness_evaluation_version_positive check (evaluation_version > 0),
  constraint readiness_evaluation_lifecycle_ck check (
    lifecycle_status in ('CREATED','EVALUATING','EVALUATED','REVIEW_REQUIRED','HUMAN_APPROVAL','DECIDED','SUPERSEDED')
  ),
  constraint readiness_evaluation_result_ck check (
    system_result in ('READY','NOT_READY','CONDITIONAL','NOT_APPLICABLE','REVIEW_REQUIRED','HUMAN_APPROVAL')
  ),
  constraint readiness_evaluation_unique_version unique (shipment_id, evaluation_version)
);

create table logistics.readiness_rule_result (
  readiness_rule_result_id bigint generated by default as identity primary key,
  readiness_evaluation_id bigint not null references logistics.readiness_evaluation(readiness_evaluation_id),
  rule_code text not null,
  rule_set_version text not null,
  result_status text not null,
  blocking boolean not null default false,
  reason text,
  explanation text,
  evaluated_at timestamptz,
  created_at timestamptz not null default now(),
  constraint readiness_rule_result_status_ck check (
    result_status in ('PASS','FAIL','WARNING','NOT_APPLICABLE','REVIEW_REQUIRED')
  ),
  constraint readiness_rule_result_unique unique (readiness_evaluation_id, rule_code, rule_set_version)
);

create table logistics.readiness_evidence_reference (
  readiness_evidence_reference_id bigint generated by default as identity primary key,
  readiness_rule_result_id bigint not null references logistics.readiness_rule_result(readiness_rule_result_id),
  shipment_id bigint not null references logistics.shipments(shipment_id),

  shipment_cargo_id bigint references logistics.shipment_cargo(shipment_cargo_id),
  shipment_container_id bigint references logistics.shipment_container(shipment_container_id),
  container_vgm_id bigint references logistics.container_vgm(container_vgm_id),
  weighbridge_record_id bigint references logistics.weighbridge_record(weighbridge_record_id),
  stuffing_record_id bigint references logistics.stuffing_record(stuffing_record_id),
  tracking_event_id bigint references logistics.tracking_event(tracking_event_id),
  shipment_milestone_id bigint references logistics.shipment_milestone(shipment_milestone_id),
  shipment_exception_id bigint references logistics.shipment_exception(shipment_exception_id),
  shipment_leg_id bigint references logistics.shipment_legs(shipment_leg_id),
  shipment_document_id bigint references logistics.shipment_documents(shipment_document_id),
  delivery_id bigint references logistics.delivery(delivery_id),
  proof_of_delivery_id bigint references logistics.proof_of_delivery(proof_of_delivery_id),

  evidence_class text not null,
  source_status text,
  source_version text,
  source_timestamp timestamptz,
  applicability text not null default 'APPLICABLE',
  conflict_status text not null default 'NONE',
  snapshot_metadata jsonb,

  created_at timestamptz not null default now(),

  constraint readiness_evidence_applicability_ck check (
    applicability in ('APPLICABLE','NOT_APPLICABLE')
  ),
  constraint readiness_evidence_conflict_ck check (
    conflict_status in ('NONE','CONFLICTING','SUPERSEDED')
  ),
  constraint readiness_evidence_exactly_one_source_ck check (
    num_nonnulls(
      shipment_cargo_id,
      shipment_container_id,
      container_vgm_id,
      weighbridge_record_id,
      stuffing_record_id,
      tracking_event_id,
      shipment_milestone_id,
      shipment_exception_id,
      shipment_leg_id,
      shipment_document_id,
      delivery_id,
      proof_of_delivery_id
    ) = 1
  )
);

create table logistics.readiness_human_decision (
  readiness_human_decision_id bigint generated by default as identity primary key,
  readiness_evaluation_id bigint not null references logistics.readiness_evaluation(readiness_evaluation_id),
  decision text not null,
  decided_by bigint not null references logistics.users(user_id),
  decided_at timestamptz not null default now(),
  decision_reason text not null,
  created_at timestamptz not null default now(),
  constraint readiness_human_decision_ck check (
    decision in ('APPROVE','REJECT','RETURN_FOR_CORRECTION','DEFER')
  ),
  constraint readiness_human_decision_unique_evaluation unique (readiness_evaluation_id)
);

create index readiness_evaluation_shipment_idx
  on logistics.readiness_evaluation(shipment_id);

create index readiness_rule_result_evaluation_idx
  on logistics.readiness_rule_result(readiness_evaluation_id);

create index readiness_evidence_rule_result_idx
  on logistics.readiness_evidence_reference(readiness_rule_result_id);

create index readiness_human_decision_evaluation_idx
  on logistics.readiness_human_decision(readiness_evaluation_id);

alter table logistics.readiness_evaluation enable row level security;
alter table logistics.readiness_rule_result enable row level security;
alter table logistics.readiness_evidence_reference enable row level security;
alter table logistics.readiness_human_decision enable row level security;

-- No anonymous policies. No DELETE policies.
-- Exact readiness permission rows and policies are intentionally deferred until
-- the controlled environment confirms the existing RBAC catalogue and approval.

commit;
